//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anode.Localisation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class en_UK {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_UK() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Anode.Localisation.en-UK", typeof(en_UK).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutWin {
            get {
                return ResourceManager.GetString("AboutWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advance frame.
        /// </summary>
        public static string AdvFrameTool {
            get {
                return ResourceManager.GetString("AdvFrameTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anode.
        /// </summary>
        public static string AnodeName {
            get {
                return ResourceManager.GetString("AnodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An open source NES emulator built in winforms, with the intent on focusing on improving
        ///accuracy.
        /// </summary>
        public static string AnodeSummary {
            get {
                return ResourceManager.GetString("AnodeSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug tracker.
        /// </summary>
        public static string BugLink {
            get {
                return ResourceManager.GetString("BugLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © Electronacl 2026. Licensed under the MIT licence.
        ///&quot;NES&quot; and &quot;Nintendo&quot; are registered trademarks of Nintendo Co. LTD. 
        ///This program is not endorsed by, nor affiliated with, Nintendo..
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls marked with [X] are features which do not currently exist, but are planned for the future..
        /// </summary>
        public static string CoreConfigIncompatInfo {
            get {
                return ResourceManager.GetString("CoreConfigIncompatInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls marked with [/] are only compatible with specific cores..
        /// </summary>
        public static string CoreConfigPartialCompatInfo {
            get {
                return ResourceManager.GetString("CoreConfigPartialCompatInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emulator Cores.
        /// </summary>
        public static string CoresTab {
            get {
                return ResourceManager.GetString("CoresTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disabled.
        /// </summary>
        public static string DisabledCommonTool {
            get {
                return ResourceManager.GetString("DisabledCommonTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emulation.
        /// </summary>
        public static string EmulationMenu {
            get {
                return ResourceManager.GetString("EmulationMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enabled.
        /// </summary>
        public static string EnabledCommonTool {
            get {
                return ResourceManager.GetString("EnabledCommonTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string FileMenu {
            get {
                return ResourceManager.GetString("FileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string GeneralTab {
            get {
                return ResourceManager.GetString("GeneralTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub.
        /// </summary>
        public static string GitHubLink {
            get {
                return ResourceManager.GetString("GitHubLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard reset.
        /// </summary>
        public static string HardResetTool {
            get {
                return ResourceManager.GetString("HardResetTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageControl {
            get {
                return ResourceManager.GetString("LanguageControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal info: Whilst making, using, and running an emulator is legal, this only applies if the ROMs
        ///used are legally obtained. This emulator is only intended to run legally obtained ROMs, and the
        ///developer assumes no responsibility for any ROMs loaded onto this emulator..
        /// </summary>
        public static string LegalInfo {
            get {
                return ResourceManager.GetString("LegalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string LicenseLink {
            get {
                return ResourceManager.GetString("LicenseLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localisation.
        /// </summary>
        public static string LocalisationGroup {
            get {
                return ResourceManager.GetString("LocalisationGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here, you can change the app&apos;s language. Currently, localisation is extremely limited, so do not expect many strings to be translated..
        /// </summary>
        public static string LocalisationGroupDesc {
            get {
                return ResourceManager.GetString("LocalisationGroupDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANE Magic:.
        /// </summary>
        public static string NESANEMagic {
            get {
                return ResourceManager.GetString("NESANEMagic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all NESes are identical. For that reason, you might want to emulate a specific console variant if you want to run certain games..
        /// </summary>
        public static string NESConfigGroupDesc {
            get {
                return ResourceManager.GetString("NESConfigGroupDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!] Some specific hardware combinations may not exist for actual hardware, or may not be intended for standard NESes.
        /// </summary>
        public static string NESConfigWarn {
            get {
                return ResourceManager.GetString("NESConfigWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose &quot;Nessie&quot; if you prefer performance, or &quot;PartialNES&quot; if you prefer accuracy..
        /// </summary>
        public static string NESCoreGroupDesc {
            get {
                return ResourceManager.GetString("NESCoreGroupDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU Era:.
        /// </summary>
        public static string NESCPUYear {
            get {
                return ResourceManager.GetString("NESCPUYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LXA Magic:.
        /// </summary>
        public static string NESLXAMagic {
            get {
                return ResourceManager.GetString("NESLXAMagic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NES.
        /// </summary>
        public static string NESName {
            get {
                return ResourceManager.GetString("NESName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mid-1990s.
        /// </summary>
        public static string NESNEWCPU {
            get {
                return ResourceManager.GetString("NESNEWCPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NTSC PPU Revision:.
        /// </summary>
        public static string NESNTSCPPURev {
            get {
                return ResourceManager.GetString("NESNTSCPPURev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NTSC Console:.
        /// </summary>
        public static string NESNTSCType {
            get {
                return ResourceManager.GetString("NESNTSCType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-mid-1990s.
        /// </summary>
        public static string NESOLDCPU {
            get {
                return ResourceManager.GetString("NESOLDCPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAL PPU Revision:.
        /// </summary>
        public static string NESPALPPURev {
            get {
                return ResourceManager.GetString("NESPALPPURev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All FF.
        /// </summary>
        public static string NESRAMFF {
            get {
                return ResourceManager.GetString("NESRAMFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power-on RAM.
        /// </summary>
        public static string NESRAMMode {
            get {
                return ResourceManager.GetString("NESRAMMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8x F0-F0-0F-0F, 8x inverse.
        /// </summary>
        public static string NESRAMNybbleAlternate {
            get {
                return ResourceManager.GetString("NESRAMNybbleAlternate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All 00.
        /// </summary>
        public static string NESRAMZero {
            get {
                return ResourceManager.GetString("NESRAMZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4x 00, 4x FF.
        /// </summary>
        public static string NESRRAMAlternate {
            get {
                return ResourceManager.GetString("NESRRAMAlternate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!] Nessie is currently &quot;experimental&quot;, and can often crash or fail to run.
        /// </summary>
        public static string NessieExperimentalWarn {
            get {
                return ResourceManager.GetString("NessieExperimentalWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nessie.
        /// </summary>
        public static string NessieName {
            get {
                return ResourceManager.GetString("NessieName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string OpenTool {
            get {
                return ResourceManager.GetString("OpenTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string OptionsWin {
            get {
                return ResourceManager.GetString("OptionsWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!] PartialNES is marked for deprecation in 2.0.0, and will no longer be available after..
        /// </summary>
        public static string PartialNESDeprWarn {
            get {
                return ResourceManager.GetString("PartialNESDeprWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartialNES.
        /// </summary>
        public static string PartialNESName {
            get {
                return ResourceManager.GetString("PartialNESName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string PauseTool1 {
            get {
                return ResourceManager.GetString("PauseTool1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string PauseTool2 {
            get {
                return ResourceManager.GetString("PauseTool2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use defaults.
        /// </summary>
        public static string ResetConfig {
            get {
                return ResourceManager.GetString("ResetConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100.
        /// </summary>
        public static string ThisTranslationPercentage {
            get {
                return ResourceManager.GetString("ThisTranslationPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throttler.
        /// </summary>
        public static string ThrottlerTool {
            get {
                return ResourceManager.GetString("ThrottlerTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: .
        /// </summary>
        public static string VersionText {
            get {
                return ResourceManager.GetString("VersionText", resourceCulture);
            }
        }
    }
}
